spring:
  rabbitmq:
    password: VE3Qm-pgdG1j2XxQRbCC6mqC2CuU-dj7
    username: uhbceumm
    virtual-host: uhbceumm
  zipkin:
    rabbitmq:
      addresses: toad.rmq.cloudamqp.com
    sender:
      type: rabbit