eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8775

spring:
  rabbitmq:
    password: VE3Qm-pgdG1j2XxQRbCC6mqC2CuU-dj7
    username: uhbceumm
    virtual-host: uhbceumm
  zipkin:
    rabbitmq:
      addresses: toad.rmq.cloudamqp.com
    sender:
      type: rabbit

  cloud:
    gateway:
      routes:
      - id: route_security
        uri: lb://spring-cloud-ms-security
        predicates:
        - Path=/route/mssecurity/**
        filters:
        - StripPrefix=1

      - id: route_security2
        uri: lb://spring-cloud-ms-security
        predicates:
        - Path=/mssecurity/**

      - id: route_mspersona
        uri: lb://spring-cloud-ms-persona
        predicates:
        - Path=/route/ms-persona/**
        filters:
        - StripPrefix=1

      - id: route_msconsulta2
        uri: lb://spring-cloud-ms-exp-consulta
        predicates:
        - Path=/route/msexpconsulta/**
        filters:
        - StripPrefix=1

      - id: route_ms_exp_pago
        uri: lb://spring-cloud-ms-exp-pago
        predicates:
        - Path=/route/msbpago/**
        filters:
        - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"